server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Igorgcf/EAD-Config-Server-Repo
  output:
    ansi:
      enabled: always

ead:
  configserver:
    username: configserver
    password: ead-secret
  serviceRegistry:
    username: ead-admin
    password: ead-secret

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://ead-admin:ead-secret@localhost:8761/eureka'
  instance:
    hostname: localhost

